name: ebay-config
api.sandbox.ebay.com:
    appid: EdwardMu-CharityP-PRD-538907625-4999b865
    certid: PRD-38907625e4e8-b6b8-4c83-b069-68ac
    devid: f21ad267-e241-4ed0-8943-721fa90bcf3a
    redirecturi: Edward_Muldrew-EdwardMu-Charit-snkpen

Api.ebay.com:
    appid: EdwardMu-CharityP-PRD-538907625-4999b865
    certid: PRD-38907625e4e8-b6b8-4c83-b069-68ac
    devid: f21ad267-e241-4ed0-8943-721fa90bcf3a
    redirecturi: Edward_Muldrew-EdwardMu-Charit-snkpen